function [val,ll]=loglik2_T5(parhat,y1,y2,y3,y4,y5,X1,X2,X3,X4,X5,...
    Z1,Z2,Z3,Z4,Z5,M,N,detval)
    
    %For speed use the Pace and Barry (1999) approximation instead of the
        %direct computation of the log-determinant 
    %gsize=detval(2,1)-detval(1,1);
    %i1=find(detval(:,1)<=parhat(2)+gsize);
    %i2=find(detval(:,1)<=parhat(2)-gsize);
    %i1=max(i1);
    %i2=max(i2);
    %index=round((i1+i2)/2);
    %if isempty(index)
    %index=1;
    %end
    %detm=detval(index,2); 
    
    I=eye(N);
    detm=log(det(I-parhat(2)*M));

    Mphi=inv((I-parhat(6)*M));
    matvar=parhat(8)*Mphi*transpose(Mphi);
   
    epsilon1=y1-X1*parhat(1)-M*y1*parhat(2)-M*X1*parhat(3);
    htilde1=((I-parhat(5)*M)^(-1))*exp(Z1*parhat(4));
    sigmastar1=1/(transpose(htilde1)*(matvar)^(-1)*htilde1+(1/(parhat(7))));
    mustar1=(-transpose(epsilon1)*(matvar)^(-1)*htilde1)/...
        (transpose(htilde1)*(matvar)^(-1)*htilde1+(1/(parhat(7)))); 
    v1=detm-(N/2)*log(2*pi)-(1/2)*(log(det(matvar)))...
        -(1/2)*(transpose(epsilon1)*(matvar)^(-1)*epsilon1)+(1/2)...
        *((mustar1.^2)/sigmastar1)+log(sqrt(sigmastar1)...
        *normcdf(mustar1./sqrt(sigmastar1)))-log(sqrt(parhat(7))*0.5);            
    l1=(1/N)*detm-(1/2)*log(2*pi)-(1/(2*N))*(log(det(matvar)))...
        -(1/2)*((matvar)^(-1)*(epsilon1.^2))+(1/(2*N))...
        *((mustar1.^2)./sigmastar1)+(1/N)*log(sqrt(sigmastar1)...
        .*normcdf(mustar1./sqrt(sigmastar1)))-(1/N)*log(sqrt(parhat(7))*0.5);            
    
    epsilon2=y2-X2*parhat(1)-M*y2*parhat(2)-M*X2*parhat(3);
    htilde2=((I-parhat(5)*M)^(-1))*exp(Z2*parhat(4));
    sigmastar2=1/(transpose(htilde2)*(matvar)^(-1)*htilde2+(1/(parhat(7))));
    mustar2=(-transpose(epsilon2)*(matvar)^(-1)*htilde2)/...
        (transpose(htilde2)*(matvar)^(-1)*htilde2+(1/(parhat(7)))); 
    v2=detm-(N/2)*log(2*pi)-(1/2)*(log(det(matvar)))...
        -(1/2)*(transpose(epsilon2)*(matvar)^(-1)*epsilon2)+(1/2)...
        *((mustar2.^2)/sigmastar2)+log(sqrt(sigmastar2)...
        *normcdf(mustar2./sqrt(sigmastar2)))-log(sqrt(parhat(7))*0.5);    
    l2=(1/N)*detm-(1/2)*log(2*pi)-(1/(2*N))*(log(det(matvar)))...
        -(1/2)*((matvar)^(-1)*(epsilon2.^2))+(1/(2*N))...
        *((mustar2.^2)./sigmastar2)+(1/N)*log(sqrt(sigmastar2)...
        .*normcdf(mustar2./sqrt(sigmastar2)))-(1/N)*log(sqrt(parhat(7))*0.5);
    
    epsilon3=y3-X3*parhat(1)-M*y3*parhat(2)-M*X3*parhat(3);
    htilde3=((I-parhat(5)*M)^(-1))*exp(Z3*parhat(4));
    sigmastar3=1/(transpose(htilde3)*(matvar)^(-1)*htilde3+(1/(parhat(7))));
    mustar3=(-transpose(epsilon3)*(matvar)^(-1)*htilde3)/...
        (transpose(htilde3)*(matvar)^(-1)*htilde3+(1/(parhat(7)))); 
    v3=detm-(N/2)*log(2*pi)-(1/2)*(log(det(matvar)))...
        -(1/2)*(transpose(epsilon3)*(matvar)^(-1)*epsilon3)+(1/2)...
        *((mustar3.^2)/sigmastar3)+log(sqrt(sigmastar3)...
        *normcdf(mustar3./sqrt(sigmastar3)))-log(sqrt(parhat(7))*0.5);
    l3=(1/N)*detm-(1/2)*log(2*pi)-(1/(2*N))*(log(det(matvar)))...
        -(1/2)*((matvar)^(-1)*(epsilon3.^2))+(1/(2*N))...
        *((mustar3.^2)./sigmastar3)+(1/N)*log(sqrt(sigmastar3)...
        .*normcdf(mustar3./sqrt(sigmastar3)))-(1/N)*log(sqrt(parhat(7))*0.5);
    
    epsilon4=y4-X4*parhat(1)-M*y4*parhat(2)-M*X4*parhat(3);
    htilde4=((I-parhat(5)*M)^(-1))*exp(Z4*parhat(4));
    sigmastar4=1/(transpose(htilde4)*(matvar)^(-1)*htilde4+(1/(parhat(7))));
    mustar4=(-transpose(epsilon4)*(matvar)^(-1)*htilde4)/...
        (transpose(htilde4)*(matvar)^(-1)*htilde4+(1/(parhat(7)))); 
    v4=detm-(N/2)*log(2*pi)-(1/2)*(log(det(matvar)))...
        -(1/2)*(transpose(epsilon4)*(matvar)^(-1)*epsilon4)+(1/2)...
        *((mustar4.^2)/sigmastar4)+log(sqrt(sigmastar4)...
        *normcdf(mustar4./sqrt(sigmastar4)))-log(sqrt(parhat(7))*0.5);
    l4=(1/N)*detm-(1/2)*log(2*pi)-(1/(2*N))*(log(det(matvar)))...
        -(1/2)*((matvar)^(-1)*(epsilon4.^2))+(1/(2*N))...
        *((mustar4.^2)./sigmastar4)+(1/N)*log(sqrt(sigmastar4)...
        .*normcdf(mustar4./sqrt(sigmastar4)))-(1/N)*log(sqrt(parhat(7))*0.5);
    
    epsilon5=y5-X5*parhat(1)-M*y5*parhat(2)-M*X5*parhat(3);
    htilde5=((I-parhat(5)*M)^(-1))*exp(Z5*parhat(4));
    sigmastar5=1/(transpose(htilde5)*(matvar)^(-1)*htilde5+(1/(parhat(7))));
    mustar5=(-transpose(epsilon5)*(matvar)^(-1)*htilde5)/...
        (transpose(htilde5)*(matvar)^(-1)*htilde5+(1/(parhat(7)))); 
    v5=detm-(N/2)*log(2*pi)-(1/2)*(log(det(matvar)))...
        -(1/2)*(transpose(epsilon5)*(matvar)^(-1)*epsilon5)+(1/2)...
        *((mustar5.^2)/sigmastar5)+log(sqrt(sigmastar5)...
        *normcdf(mustar5./sqrt(sigmastar5)))-log(sqrt(parhat(7))*0.5);  
     l5=(1/N)*detm-(1/2)*log(2*pi)-(1/(2*N))*(log(det(matvar)))...
        -(1/2)*((matvar)^(-1)*(epsilon5.^2))+(1/(2*N))...
        *((mustar5.^2)./sigmastar5)+(1/N)*log(sqrt(sigmastar5)...
        .*normcdf(mustar5./sqrt(sigmastar5)))-(1/N)*log(sqrt(parhat(7))*0.5);  
        
    ll=-(l1+l2+l3+l4+l5);    
    
    val=v1+v2+v3+v4+v5;
    val=-val;
    
end